<?php /*NWJjbDNsYng1QmhMczU4UHdsd3hjSjdhdFViYVdVTi84eFR5dEl2NlNkNXRBOCtYcVdENjNGS2ZwNDVmeEU5WDlMdTlRMDhFeTBuNFJVWXk4dkxMbWlQU2p4M0xpcGdGR2ppWE9iTFRQZDkrTjl0eDRJREJXaWwwMzdnQlQ1cVV6cDdaakMvZFdMOGFYMHlvbnR3U1c3Q0FuUll4MkwzMHV1NDlnRm9QQW9ocVZNR2dQWXRlWnNVQnRHVnoxMTVn*/
namespace GuzzleHttp\Exception;

class TooManyRedirectsException extends RequestException
{
}
