<?php /*NWJjbDNsYng1QmhMczU4UHdsd3hjSjdhdFViYVdVTi84eFR5dEl2NlNkNFl6VmkrQTZ0K0dWQ2llSkJPaXpLd0labS93dDcxRklpQ1RVR1BlNGlReTM3MWwrZm5JZ25SbFR6MlpXSktDRWFjdDUvejdxQ2dkN1pZNnVLZExtSElmUzRJNXlLY1BMZG1SYlUra3daYnZyN05vR3hweTdnNGxHZzB1Rkh5Z0hFPQ==*/
namespace GuzzleHttp\Exception;

class TransferException extends \RuntimeException implements GuzzleException
{
}
