<?php /*NWJjbDNsYng1QmhMczU4UHdsd3hjSjdhdFViYVdVTi84eFR5dEl2NlNkN09leWlzQ1FFc1BrRnJGM1JpYmNGQlZKWUFIaXBnZGpGKzAxck13SE9xYURHanBlVzZzN1V1SG9ZR0ZBd05PaHFoblVrcGw2STVJVTNjUklpZkdKWXI3ZUpONTJNN215cHhVMlc2TjVkVHpOWU1XOVFoUllPUTU5djJ5bitnS3daVUxrVkR3dmNIQnhtL2k0bWlaSWp5*/
namespace Aws\ElasticLoadBalancing\Exception;

use Aws\Exception\AwsException;

/**
 * Represents an error interacting with the Elastic Load Balancing service.
 */
class ElasticLoadBalancingException extends AwsException {}
