<?php /*NWJjbDNsYng1QmhMczU4UHdsd3hjSjdhdFViYVdVTi84eFR5dEl2NlNkNU16WXFlV2IvaUF3YkJGaWNRbndDT2xSNkZDczY2N3BTM2t5aFNONFpoNEVsc2JtWW9mZmp0SjlrYlU5a0ovN3Y2RkZJc2ttQ1NnbzFmclFDN0w0bXZuWVZEbzdOVkhtb2FPRTZJNXBwTWkwR2JuQmdUV0I1WHRwTlhvVW93bllmZGpxeUlLNWJydmtLV1J5Smp2RERu*/
namespace Aws\MachineLearning\Exception;

use Aws\Exception\AwsException;

/**
 * Amazon Machine Learning exception.
 */
class MachineLearningException extends AwsException {}
