<?php /*NWJjbDNsYng1QmhMczU4UHdsd3hjSjdhdFViYVdVTi84eFR5dEl2NlNkNTE1RnJVM3BoeG0zVncrQ3dOc2JIMURodDNIUGRZQVN3aVNSOEJhS201K0NoQWpPa3NBaVNvdndWck4vR3FlbWlKOEZQbTRrcTFnb2xra3VqZ1ZhSWxJSDFnNTdtVHh5cTRnYktmWXJiY1JXcFpLMGQxWksrZlVtREtmSmVRRE51R3psRW1IbmMvQ1pnQXlqZFhHdHJaZ0RNNml4alJFbEFhK1RSb0VIa2pmdz09*/
namespace Aws\MigrationHubStrategyRecommendations\Exception;

use Aws\Exception\AwsException;

/**
 * Represents an error interacting with the **Migration Hub Strategy Recommendations** service.
 */
class MigrationHubStrategyRecommendationsException extends AwsException {}
